name: Build-Experimental

on:
  push:
    branches: experimental

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast:  true

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.tag}}
      
      - name: 'Setup Pre-Requisites & Prepare Staging Area'
        shell:  |
                pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
        run:  |
              apt-get update && apt-get install wget unzip
              cd '${{github.workspace}}'
              wget -O WolvenKit.zip 'https://github.com/WolvenKit/WolvenKit/releases/download/8.5.3/WolvenKit.Console-1.6.5.zip'
              Expand-Archive -Path WolvenKit.zip -DestinationPath .
              mv "WolvenKit CLI" WolvenKit
              mkdir '${{github.workspace}}/STAGING/archive/pc/mod'
              mkdir '${{github.workspace}}/STAGING/r6/scripts'
              cp '${{github.workspace}}/redscript/REALISTICCOMBATOVERHAUL.reds' '${{github.workspace}}/STAGING/r6/scripts'

      - name: 'Pack .archive'
        shell:  |
                pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
        run:  |
              cd '${{github.workspace}}/basegame_REALISM'
              ../WolvenKit/WolvenKit.CLI pack -p . -o '../STAGING/archive/pc/mod'
        
      - name:   'Upload Artifact'
        uses:   actions/upload-artifact@v2
        with:
          name: 'HARDCORE44-ARCO'
          path: '${{github.workspace}}/STAGING/*'
