name: 'Create Release'

on:
  push:
    tags: [ '*.*.*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: |
               pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"


    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get Version Tag'
        id:   get_version
        run:  |
              $TAG = ${GITHUB_REF/refs\/tags\//}
              echo "Version Tag: $TAG"
              echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: 'Update Project Version' # This isn't really necessary, but we might as well keep the version number up-to-date.
        run:  |
              $CPMODPROJ = $(Get-ChildItem -File -Filter *.cpmodproj).Name
              [xml]$CONTENT = Get-Content $CPMODPROJ
              $CONTENT.CP77Mod.Version = "${{ steps.get_version.outputs.tag }}"
              $CONTENT.Save($CPMODPROJ)

      - name: 'Stage Resources'
        run:  |
              mkdir packed/archive/pc/mod
              cp -Force -Recurse source/resources/* packed

      - name: 'Fix location of TweakXL YAML files'
        run:  |
              mkdir packed/r6/tweaks
              mv -Force packed/HARDCORE44 packed/r6/tweaks/HARDCORE44

      - name: 'WolvenKit: Setup CLI'
        run:  |
              Invoke-WebRequest -Method Get -Uri https://github.com/WolvenKit/WolvenKit/releases/download/8.5.3/WolvenKit.Console-1.6.5.zip -OutFile WolvenKit.zip
              Expand-Archive -Path WolvenKit.zip -DestinationPath .
              rm WolvenKit.zip
              mv "WolvenKit CLI" WolvenKit

      - name: 'WolvenKit: Pack Mod Archive'
        run:  |
              ./WolvenKit/WolvenKit.CLI.exe pack -p source/archive -o .
              mv -Force *.archive packed/archive/pc/mod/HARDCORE44.archive

      - uses: actions/upload-artifact@v3
        with:
          name: 'HARDCORE44-ARCO.zip'
          path: 'packed/*'
      
      - name: 'Create Release Archive'
        run:  |
              Compress-Archive packed/* HARDCORE44-ARCO.zip

      - name: 'Upload Release to Github'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ steps.get_version.outputs.tag }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: 'HARDCORE44-ARCO.zip'
