name: Generate-Release

on:
  push:
    tags: '*'
  workflow_dispatch:
    inputs:
      tag:
        type:     string
        default:  ''
        required: false

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast:  true

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.tag}}
          fetch-depth: 0
      
      - name:  'Setup Pre-Requisites & Prepare Staging Area'
        shell: |
               pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
        run:   |
               cd '${{github.workspace}}'
               Invoke-WebRequest -Method Get -Uri https://github.com/WolvenKit/WolvenKit/releases/download/8.5.3/WolvenKit.Console-1.6.5.zip -OutFile WolvenKit.zip
               Expand-Archive -Path WolvenKit.zip -DestinationPath .
               mv "WolvenKit CLI" WolvenKit
               mkdir '${{github.workspace}}/STAGING/archive/pc/mod'
               mkdir '${{github.workspace}}/STAGING/r6/scripts'
               cp '${{github.workspace}}/redscript/REALISTICCOMBATOVERHAUL.reds' '${{github.workspace}}/STAGING/r6/scripts'
                  
      - name:  'Pack .archive'
        shell: |
               pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
        run:   |
               cd '${{github.workspace}}/basegame_REALISM'
               ../WolvenKit/WolvenKit.CLI pack -p . -o '../STAGING/archive/pc/mod'
        
      - name:   'Upload Artifact'
        uses:   actions/upload-artifact@v2
        with:
          name: 'HARDCORE44-ARCO'
          path: '${{github.workspace}}/STAGING/*'

      - name:   'Create Release Archive'
        shell:  |
                pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
        run:    |
                cd '${{github.workspace}}/STAGING'
                Compress-Archive -Path ./* -DestinationPath "../HARDCORE44-ARCO-$TAG.zip"
            
      - name:   'Create Github Release'
        uses:   softprops/action-gh-release@v1
        with:
          draft:                    true
          prerelease:               false
          generate_release_notes:   true
          fail_on_unmatched_files:  true
          files:                    './*.zip'
