name: Generate-Release

on:
  push:
    tags: '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast:  true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: 'Prepare Staging Area'
        run:  |
              mkdir '${{ github.workspace }}/STAGING/archive/pc/mod'
              mkdir '${{ github.workspace }}/STAGING/r6/scripts'
              
      - name: 'Stage Scripts'
        run:  cp '${{ github.workspace }}/redscript/REALISTICCOMBATOVERHAUL.reds' '${{ github.workspace }}/STAGING/r6/scripts'
              
      - name:  'Setup Wolvenkit CLI'
        shell: |
               pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
        run:   |
               cd '${{ github.workspace }}'
               Invoke-WebRequest -Method Get -Uri https://github.com/WolvenKit/WolvenKit/releases/download/8.5.3/WolvenKit.Console-1.6.5.zip -OutFile WolvenKit.zip
               Expand-Archive -Path WolvenKit.zip -DestinationPath .
               mv "WolvenKit CLI" WolvenKit
               
      - name:  'Pack Mod Archive'
        shell: |
               pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
        run:   |
               cd '${{ github.workspace }}/basegame_REALISM'
               ../WolvenKit/WolvenKit.CLI pack -p . -o '../STAGING/archive/pc/mod'
        
      - uses:   actions/upload-artifact@v2
        with:
          name: 'HARDCORE44-ARCO'
          path: '${{ github.workspace }}/STAGING/*'

      - name:   'Create Release Archive'
        shell:  |
                pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
        run:    |
                cd '${{ github.workspace }}'
                $TAG=$(git describe --tags --abbrev=0)
                cd '${{ github.workspace }}/STAGING'
                Compress-Archive -Path ./* -DestinationPath "../HARDCORE44-ARCO-$TAG.zip"
          
      - name:   'Get Most Recent Tag'
        id:     get_tag
        shell:  |
                pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
        run:    |
                echo ::set-output name=VERSION::$TAG

      - name:   'Create Github Release'
        id:     make_release
        uses:   softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: '${{ github.workspace }}/*.zip'

