name: Pack-Archive

on:
  push:
    tags: '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast:  true

    steps:
      - uses: actions/checkout@v3
      
      - name: 'Setup Pre-Requisites & Prepare Staging Area'
        run:  |
              apt-get update && apt-get install wget unzip
              cd '${{github.workspace}}'
              wget 'https://github.com/WolvenKit/WolvenKit/releases/download/8.5.3/WolvenKit.ConsoleLinux-1.6.5.zip' && unzip './*.zip'
              ls -lAgh
              mv 'WolvenKit*' WolvenKit
              mkdir -p '${{github.workspace}}/STAGING/archive/pc/mod' && mkdir -p '${{github.workspace}}/STAGING/r6/scripts'
              cp '${{github.workspace}}/redscript/*.reds' '${{github.workspace}}/STAGING/r6/scripts'
              ls -lAgh
                  
      - name: 'Pack .archive'
        run:  |
              cd '${{github.workspace}}/basegame_REALISM'
              ../WolvenKit/WolvenKit.CLI pack -p . -o '../STAGING/archive/pc/mod'
        
      - name:   'Upload Artifact'
        uses:   actions/upload-artifact@v2
        with:
          name: 'HARDCORE44-ARCO'
          path: '${{github.workspace}}/STAGING/*'
